//------------------------------------------------------------------------------
// <auto-generated>
//    (c)Netapsys 2012
//    Ce code a ete genere par template T4.
//    Ne pas le modifier manuellement !
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SimpleWebApp.Common;
using System.Runtime.Serialization;

namespace SimpleWebApp.Common
{
    
    [DataContract(Name = "Produit", Namespace = "SimpleWebApp", IsReference = true)]
    
    public partial class Produit : AEntity<int>
    {
    	[DataMember()]
        public string Nom { get; set; }
    
    	[DataMember()]
        public decimal Prix { get; set; }
    
    
    
    }
    
}
