//------------------------------------------------------------------------------
// <auto-generated>
//    (c)Netapsys 2012
//    Ce code a ete genere par template T4.
//    Ne pas le modifier manuellement !
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SimpleWebApp.Common;
using System.Runtime.Serialization;

namespace SimpleWebApp.Common
{
    
    [DataContract(Name = "TokenEntity", Namespace = "SimpleWebApp", IsReference = true)]
    
    public partial class TokenEntity : AEntity<int>
    {
    	[DataMember()]
        public int UtilisateurId { get; set; }
    
    	[DataMember()]
        public string AuthToken { get; set; }
    
    	[DataMember()]
        public System.DateTime DateCreation { get; set; }
    
    	[DataMember()]
        public System.DateTime DateExpiration { get; set; }
    
    
    
    	[DataMember()]
    	public virtual Utilisateur Utilisateur { get; set; }
    
    }
    
}
