//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using SimpleWebApp.Common;
using SimpleWebApp.Common.Unity;

using Microsoft.Practices.Unity;

namespace SimpleWebApp.Data
{
	public partial class RepositoryUnityConfigurator : IUnityConfigurator
	{
		public RepositoryUnityConfigurator()
		{
		}

		public void Configure(Microsoft.Practices.Unity.IUnityContainer container)
		{

            //Register the contexts
            container.RegisterType<SimpleWebAppEntities>(new PerResolveLifetimeManager());

            //Register the repositories
			container.RegisterType<IRepository<Produit>,RProduit>(new PerResolveLifetimeManager());
			container.RegisterType<IRepository<Role>,RRole>(new PerResolveLifetimeManager());
			container.RegisterType<IRepository<TokenEntity>,RTokenEntity>(new PerResolveLifetimeManager());
			container.RegisterType<IRepository<Utilisateur>,RUtilisateur>(new PerResolveLifetimeManager());

		}
	}
}


