//------------------------------------------------------------------------------
// <auto-generated>
//    (c)Netapsys 2012
//    Ce code a ete genere par template T4.
//    Ne pas le modifier manuellement !
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SimpleWebApp.Common;
using System.Runtime.Serialization;
using System.Xml.Linq;
using System.Linq;
using System.Data.Entity;
using log4net;


namespace SimpleWebApp.Data
{
    public partial class RRole : ARepository<Role,int> , IRepository<Role>
    {
    
    
    	#region Constructor(s)
    
    	public RRole(SimpleWebAppEntities context) : base(context){}
    
    	#endregion
    
        #region Overrided Methods
    
        public override Role GetById(int id)
        {
            return Single(id);
        }
    
        #endregion
    
    	#region Mapping
    
    	protected override void Map(Role source, Role target){
    		if(!Object.Equals(source.Libelle,target.Libelle)){
    			target.Libelle = source.Libelle;
    		}        
    	}
    
    	#endregion
    }
    }
