//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SimpleWebApp.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using log4net;

namespace SimpleWebApp.Data
{
    public partial class SimpleWebAppEntities : DbContext, IDisposable
    {
    
        /// <summary>
        /// Ctor
        /// </summary>
        public SimpleWebAppEntities()
            : base("name=SimpleWebAppEntities")
        {
    
        }
    
        /// <summary>
        /// Dtor
        /// </summary>
        ~SimpleWebAppEntities(){
    		Dispose();
        }
    
    	/// <summary>
        /// Accéder à <see cref="T:System.Data.Entity.Core.Objects"/> sous-jacent au DbContext.
        /// </summary>
        /// <returns></returns>
    	public ObjectContext ObjectContext
        {
    		get
    		{
    			return (this as IObjectContextAdapter).ObjectContext;
    		}
        }
    
    	public bool SetChangeTrackerUse
        {
            set
            {
                this.Configuration.AutoDetectChangesEnabled = value;
            }
        }
    
        /// <summary>
        /// IDisposable impl
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    
        public DbSet<Role> Role { get; set; }
        public DbSet<Utilisateur> Utilisateur { get; set; }
        public DbSet<Produit> Produit { get; set; }
        public DbSet<TokenEntity> Token { get; set; }
    
    
    }
}
